Updating scripts to use wal theme

diff --git a/.config/local/bin/pbweather b/.config/local/bin/pbweather
--- a/.config/local/bin/pbweather
+++ b/.config/local/bin/pbweather
@@ -20,8 +20,6 @@
 # Treat unset Vars as error
 set -o nounset
 
-
-
 # Based on http://openweathermap.org/current
 
 # weatherinfo file should contain these variables, city ID and API key
@@ -43,7 +41,7 @@ UPDATED="2018-08-30"
 PBWEATHER_GLOBAL_CONFIG="/etc/pbweather/pbweather.conf"
 PBWEATHER_USER_CONFIG="$HOME/.config/pbweather/pbweather.conf"
 
-. "$XDG_CONFIG_HOME/cache/wal/colors.sh"
+. "${XDG_CONFIG_HOME:-$HOME/.config}/cache/wal/colors.sh"
 # TODO: Change to def values, make it configurable in conf -> check if set else default
 
 ICON_SUNNY=""
@@ -55,7 +53,6 @@ ICON_FOG=""
 
 URGENT_LOWER=0
 URGENT_HIGHER=30
-
 
 SYMBOL_CELSIUS="°C"
 
@@ -82,42 +79,40 @@ OPTIONS
 #***  FUNCTION  ****************************************************************
 #          NAME:  wait_network
 #   DESCRIPTION:  waits for network connection: 10 attempts with 2 sec sleep betw.
-#    PARAMETERS:  
-#       RETURNS:  
+#    PARAMETERS:
+#       RETURNS:
 #*******************************************************************************
 
-wait_network(){
+wait_network() {
 
-  max_attempts=10
-  count=0
-  resp=2
+	max_attempts=10
+	count=0
+	resp=2
 
-  while [ ! "$resp" -eq 0 ]; do
+	while [ ! "$resp" -eq 0 ]; do
 
-     if [ "$count" -eq "$max_attempts" ]; then
+		if [ "$count" -eq "$max_attempts" ]; then
 
-        echo "no conn to openweathermap.org"
-	     notify-send -u critical "pbweather: Keine Verbindung zum openweathermap Server!"
-	     return 2;
+			echo "no conn to openweathermap.org"
+			notify-send -u critical "pbweather: Keine Verbindung zum openweathermap Server!"
+			return 2
 
-     fi
+		fi
 
-     ping -q -c 1 -W 1 openweathermap.org &> /dev/null
-     resp="$?"
+		ping -q -c 1 -W 1 openweathermap.org &>/dev/null
+		resp="$?"
 
-     # could not reach openweathermap.org
-     if [ ! "$resp" -eq 0 ]; then
+		# could not reach openweathermap.org
+		if [ ! "$resp" -eq 0 ]; then
 
-        count=$((count+1))
-        sleep 2;
+			count=$((count + 1))
+			sleep 2
 
-     fi
+		fi
 
-  done
-  return 0
+	done
+	return 0
 }
-
-
 
 #***  FUNCTION  ****************************************************************
 #          NAME:  loadWeather
@@ -126,21 +121,20 @@ wait_network(){
 #       RETURNS:
 #*******************************************************************************
 
-loadWeather(){
+loadWeather() {
 
-  wait_network
-  if [ "$?" -eq 2 ]; then
-      exit 2;
-  fi
+	wait_network
+	if [ "$?" -eq 2 ]; then
+		exit 2
+	fi
 
-  WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"
-  WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
+	WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"
+	WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
 
-  WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-zA-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
-  WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
+	WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-zA-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
+	WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
 
-
-  parseOpenWeathermapResponse "$WEATHER_MAIN" "$WEATHER_TEMP"
+	parseOpenWeathermapResponse "$WEATHER_MAIN" "$WEATHER_TEMP"
 
 }
 
@@ -151,47 +145,47 @@ loadWeather(){
 #       RETURNS:
 #*******************************************************************************
 
-parseOpenWeathermapResponse(){
+parseOpenWeathermapResponse() {
 
-  WEATHER_MAIN="$1"
-  WEATHER_TEMP="$2"
+	WEATHER_MAIN="$1"
+	WEATHER_TEMP="$2"
 
-  if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
+	if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
 
-    echo "%{F$(echo $color7 | cut -d '#' -f 2)}${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
+		echo "%{F$(echo $color7 | cut -d '#' -f 2)}${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
 
-  elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
+	elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
 
-    echo "%{F$(echo $color6 | cut -d '#' -f 2)}${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
+		echo "%{F$(echo $color6 | cut -d '#' -f 2)}${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
 
-  elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
+	elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
 
-    echo "%{F$(echo $color4 | cut -d '#' -f 2)}${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
+		echo "%{F$(echo $color4 | cut -d '#' -f 2)}${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
 
-  elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
+	elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
 
-    echo "%{F$(echo $color3 | cut -d '#' -f 2)}${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
+		echo "%{F$(echo $color3 | cut -d '#' -f 2)}${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
 
-  elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
+	elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
 
-    echo "%{F$(echo $color7 | cut -d '#' -f 2)}${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
+		echo "%{F$(echo $color7 | cut -d '#' -f 2)}${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
 
-  elif [[ "${WEATHER_MAIN}" = *Storm* ]]; then
+	elif [[ "${WEATHER_MAIN}" = *Storm* ]]; then
 
-   echo "%{F$(echo $color10 | cut -d '#' -f 2)}${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
+		echo "%{F$(echo $color10 | cut -d '#' -f 2)}${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F444444}"
 
-  else
+	else
 
-    echo ""
-    notify-send -u critical "Konnte Wetterdaten nicht parsen!"
+		echo ""
+		notify-send -u critical "Konnte Wetterdaten nicht parsen!"
 
-  fi
+	fi
 
-  if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
+	if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
 
-    exit 33
+		exit 33
 
-  fi
+	fi
 
 }
 #***  FUNCTION  ****************************************************************
@@ -201,9 +195,9 @@ parseOpenWeathermapResponse(){
 #       RETURNS:
 #*******************************************************************************
 
-printInfo(){
+printInfo() {
 
-  printf '%s' "${about}" | awk 'BEGIN{ind=0}
+	printf '%s' "${about}" | awk 'BEGIN{ind=0}
                                 $0~/^```/{
                                    if(ind!="1"){ind="1"}
                                    else{ind="0"}
@@ -224,20 +218,20 @@ printInfo(){
 #       RETURNS:
 #*******************************************************************************
 
-sourceConfigfile(){
+sourceConfigfile() {
 
-   if [ -f "$PBWEATHER_USER_CONFIG" ]; then
-      source "$PBWEATHER_USER_CONFIG"
-      return $?
-   elif [ -f "$PBWEATHER_GLOBAL_CONFIG" ]; then
-      source "$PBWEATHER_GLOBAL_CONFIG"
-      return $?
-   else
-      echo ""
-      echo "No config File found"
-      echo ""
-      exit 1
-   fi
+	if [ -f "$PBWEATHER_USER_CONFIG" ]; then
+		source "$PBWEATHER_USER_CONFIG"
+		return $?
+	elif [ -f "$PBWEATHER_GLOBAL_CONFIG" ]; then
+		source "$PBWEATHER_GLOBAL_CONFIG"
+		return $?
+	else
+		echo ""
+		echo "No config File found"
+		echo ""
+		exit 1
+	fi
 
 }
 
@@ -248,29 +242,29 @@ sourceConfigfile(){
 #       RETURNS:
 #*******************************************************************************
 
-main(){
-   sourceConfigfile
-   if [ "$?" -eq 2 ]; then
-      echo "Could not load settings from config files!"
-      echo "Check that either ""$PBWEATHER_USER_CONFIG"" or ""$PBWEATHER_GLOBAL_CONFIG"" exists."
-   fi
-   loadWeather
+main() {
+	sourceConfigfile
+	if [ "$?" -eq 2 ]; then
+		echo "Could not load settings from config files!"
+		echo "Check that either ""$PBWEATHER_USER_CONFIG"" or ""$PBWEATHER_GLOBAL_CONFIG"" exists."
+	fi
+	loadWeather
 }
-
-
 
 #*******************************************************************************
 #            getopts
 #*******************************************************************************
 
 while getopts :vh option; do
-   case "${option}" in
-      v) printf '%s\n' \
-           "$NAME - version: $VERSION" \
-           "updated: $UPDATED by $AUTHOR"
-         exit ;;
-      h|*) printInfo && exit ;;
-    esac
-  done
+	case "${option}" in
+	v)
+		printf '%s\n' \
+			"$NAME - version: $VERSION" \
+			"updated: $UPDATED by $AUTHOR"
+		exit
+		;;
+	h | *) printInfo && exit ;;
+	esac
+done
 
 main
